import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import { Footer } from "@/src/layout/Footer";
import { Header } from "@/src/layout/Header";
import { ThemeProvider } from "@/src/theme/ThemeProvider";
import clsx from "clsx";
import type { ReactNode } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

type LayoutProps = {
	children: ReactNode;
};

export default function RootLayout({ children }: LayoutProps) {
	return (
		<html lang="en">
			<body className={clsx(inter.className, "bg-background h-full")}>
				<ThemeProvider attribute="class" defaultTheme="system" enableSystem>
					<div className="flex flex-col h-full">
						<Header />
						<div className="flex-1 max-w-lg m-auto py-14 w-full">
							{children}
						</div>
						<Footer />
					</div>
					<Toaster />
				</ThemeProvider>
			</body>
		</html>
	);
}
